export const S3_TEMPORARY_FILES_BUCKET_KEY = 'S3_TEMPORARY_FILES_BUCKET_KEY'
export const S3_PERMANENT_FILES_BUCKET_KEY = 'S3_PERMANENT_FILES_BUCKET_KEY'
export const DYNAMODB_METADATA_TABLE_KEY = 'DYNAMODB_METADATA_TABLE_KEY'
